### ISSUE TITLE
Compiling error

### ISSUE THREAD

**Issue by clsgithubusr** [ComparativeGenomicsToolkit/hal2vg#11]
Hi

I'm receiving an error when compiling hal2vg

$ make test

h5c++  -O3 -g -Wall -funroll-loops -DNDEBUG -std=c++11 -I /tools/eb/software/sonLib/1.1.0-foss-2018b/lib  -I /tools/eb/software/HAL/2.1-foss-2018b/lib -I /tools/eb/software/hal2sg/11202018-foss-2018b/sgExport -I /tools/eb/software/hal2sg/11202018-foss-2018b -I /tools/eb/software/vg/11062018-foss-2018b/include -I /tools/eb/software/vg/11062018-foss-2018b/src -UNDEBUG -I . hal2vg.cpp -c
In file included from /gpfs/gssgpfs1/biogrid/tools/eb/software/GCCcore/7.3.0/include/c++/7.3.0/cassert:44:0,
                 from /tools/eb/software/hal2sg/11202018-foss-2018b/sgExport/sgcommon.h:11,
                 from /tools/eb/software/hal2sg/11202018-foss-2018b/sgExport/sgsequence.h:11,
                 from /tools/eb/software/hal2sg/11202018-foss-2018b/sgExport/sgposition.h:11,
                 from /tools/eb/software/hal2sg/11202018-foss-2018b/sgExport/sgside.h:10,
                 from /tools/eb/software/hal2sg/11202018-foss-2018b/sgExport/sgjoin.h:10,
                 from /tools/eb/software/hal2sg/11202018-foss-2018b/sgExport/sidegraph.h:24,
                 from /tools/eb/software/hal2sg/11202018-foss-2018b/sgbuilder.h:11,
                 from hal2vg.cpp:16:
/tools/eb/software/hal2sg/11202018-foss-2018b/sglookback.h: In member function ‘std::__cxx11::string SGLookBack::getHalGenomeName(const SGSequence*) const’:
/tools/eb/software/hal2sg/11202018-foss-2018b/sglookback.h:58:25: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
   assert(sgSeq->getID() < _halSeqMap.size());
          ~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~
hal2vg.cpp: In function ‘int main(int, char**)’:
hal2vg.cpp:258:32: error: invalid conversion from ‘std::set<const hal::Sequence*>*’ to ‘hal_index_t {aka long int}’ [-fpermissive]
                         i == 0 ? &refSequences : NULL);
                                ^
In file included from hal2vg.cpp:16:0:
/tools/eb/software/hal2sg/11202018-foss-2018b/sgbuilder.h:51:9: note:   initializing argument 3 of ‘void SGBuilder::addGenome(const hal::Genome*, const hal::Sequence*, hal_index_t, hal_index_t)’
    void addGenome(const hal::Genome* genome,
         ^~~~~~~~~
make: *** [hal2vg.o] Error 1



Can someone help me please?

**Comment by glennhickey** [comment]
This source file is no longer in hal2vg
