### ISSUE TITLE
libprotobuf.a no longer in vg

### ISSUE THREAD

**Issue by johnlees** [ComparativeGenomicsToolkit/hal2vg#17]
When installing this with a recent vg, it looks like it doesn't have the static libprotobuf library any more (using https://github.com/vgteam/vg/commit/869c9e4a1308e174e725683ee4917161b788748b).

There were two steps needed which might be helpful to add to the README:
1. Run `make static` in the `../vg` directory
2. Change `LIBPROTOBUF=$(VGLIBDIR)/libprotobuf.a` to `LIBPROTOBUF=/usr/lib/x86_64-linux-gnu/libprotobuf.a` in `include.mk`.

For `LIBPROTOBUF` you need to use the same one that you build `vg` with. If it's a system-wide install you can find it with (on Ubuntu): `dpkg -L libprotobuf-dev`

**Comment by glennhickey** [comment]
Thanks!  I updated the README with these suggestions here: https://github.com/ComparativeGenomicsToolkit/hal2vg/commit/fb3b4373eaf4b0553e021c8902273782b6d51f5c

I want to overhaul `hal2vg` to write directly to more efficient binary formats and not go through protobuf.  This is the direction vg's going in as well.  It's implemented here in https://github.com/ComparativeGenomicsToolkit/hal2vg/pull/16 which ditches the protobuf dependency entirely.
