### ISSUE TITLE
Binary release

### ISSUE THREAD

**Issue by glennhickey** [ComparativeGenomicsToolkit/hal2vg#18]
I floated the idea to @diekhans of including hal2vg in cactus.  But perhaps it'd be smartest just to make a static binary release here?  It could then be linked to from the Cactus readme or something.

**Comment by Nheyer** [comment]
I would second ether of these two options

**Comment by glennhickey** [comment]
Binary release now available.  I think I will stick it into future cactus releases as a convenience as well.
