### ISSUE TITLE
Option to avoid reference cycles

### ISSUE THREAD

**Issue by glennhickey** [ComparativeGenomicsToolkit/hal2vg#4]
Once --refGenome (#1) works, people will be able to use non-root genomes as references again.  These will generally contain paralogies which get converted into vg cycles.  As it stands, vg doesn't cope to well with cycles, especially in the reference.  Should add option to ignore paralogies in the reference, or perhaps altogether.

**Comment by adamnovak** [comment]
The important thing would be to allow there to be "duplications" between alt contigs and primary contigs, while preventing pieces of the same primary chromosome (or maybe of two different primary chromosomes) from overlapping.

**Comment by glennhickey** [comment]
OK, this is working as a blanket hal genome wide switch (off by default) for reference duplications.   It will only process alt contigs the way you want if they are in a separate hal genome.  Otherwise, will need to pass in a list of primary contig names, I guess.

**Comment by glennhickey** [comment]
--refSequenceFile added to pass a list of reference sequence names.  A file containing chr1, chr2, etc. can be used to make sure these contigs are not folded into cycles.  But everything else, ex the alts, get aligned to them and each other when possible.
