### ISSUE TITLE
 more undefined references to `vg::Graph::~Graph()' follow

### ISSUE THREAD

**Issue by fbemm** [ComparativeGenomicsToolkit/hal2vg#6]
I am trying to compile hal2vg with the latest vgtools commit and get the following:

make[1]: Entering directory `hal2vg/deps/hal2sg'
make[1]: Nothing to be done for `all'.
make[1]: Leaving directory `hal2vg/deps/hal2sg'
h5c++  -O3 -g -Wall -funroll-loops -DNDEBUG -std=c++11 -I deps/sonLib/lib  -I deps/hal/lib -I .//deps/hal2sg/sgExport -I .//deps/hal2sg -I ../vg/include -UNDEBUG hal2vg.o sg2vgproto.o .//deps/hal2sg/libhal2sg.a .//deps/hal2sg/sgExport/sgExport.a deps/hal/lib/halLiftover.a deps/hal/lib/halLib.a ../vg/lib/libvg.a ../vg/lib/libprotobuf.a deps/sonLib/lib/sonLib.a deps/sonLib/lib/cuTest.a   -o hal2vg
sg2vgproto.o: In function `operator()':
hal2vg/sg2vgproto.cpp:61: undefined reference to `vg::Graph::Graph(vg::Graph const&)'
sg2vgproto.o: In function `vg::Node* google::protobuf::Arena::CreateInternal<vg::Node>(bool)':
vg/include/google/protobuf/arena.h:645: undefined reference to `typeinfo for vg::Node'
vg/include/google/protobuf/arena.h:645: undefined reference to `vg::Node::Node()'
sg2vgproto.o: In function `google::protobuf::internal::GenericTypeHandler<vg::Node>::New(google::protobuf::Arena*)':
vg/include/google/protobuf/arena.h:308: undefined reference to `vg::Node::Node()'
sg2vgproto.o: In function `vg::Edge* google::protobuf::Arena::CreateInternal<vg::Edge>(bool)':
vg/include/google/protobuf/arena.h:645: undefined reference to `typeinfo for vg::Edge'
vg/include/google/protobuf/arena.h:645: undefined reference to `vg::Edge::Edge()'
sg2vgproto.o: In function `google::protobuf::internal::GenericTypeHandler<vg::Edge>::New(google::protobuf::Arena*)':
vg/include/google/protobuf/arena.h:308: undefined reference to `vg::Edge::Edge()'
sg2vgproto.o: In function `vg::Path* google::protobuf::Arena::CreateInternal<vg::Path>(bool)':
vg/include/google/protobuf/arena.h:645: undefined reference to `typeinfo for vg::Path'
vg/include/google/protobuf/arena.h:645: undefined reference to `vg::Path::Path()'
sg2vgproto.o: In function `google::protobuf::internal::GenericTypeHandler<vg::Path>::New(google::protobuf::Arena*)':
vg/include/google/protobuf/arena.h:308: undefined reference to `vg::Path::Path()'
sg2vgproto.o: In function `vg::Mapping* google::protobuf::Arena::CreateInternal<vg::Mapping>(bool)':
vg/include/google/protobuf/arena.h:645: undefined reference to `typeinfo for vg::Mapping'
vg/include/google/protobuf/arena.h:645: undefined reference to `vg::Mapping::Mapping()'
sg2vgproto.o: In function `google::protobuf::internal::GenericTypeHandler<vg::Mapping>::New(google::protobuf::Arena*)':
vg/include/google/protobuf/arena.h:308: undefined reference to `vg::Mapping::Mapping()'
sg2vgproto.o: In function `SG2VGProto::SG2VGProto()':
hal2vg/sg2vgproto.cpp:17: undefined reference to `vg::Graph::Graph()'
sg2vgproto.o: In function `vg::Mapping::mutable_position()':
vg/include/vg.pb.h:3227: undefined reference to `vg::Position::Position()'
sg2vgproto.o: In function `SG2VGProto::init(std::ostream*)':
hal2vg/sg2vgproto.cpp:29: undefined reference to `vg::Graph::Graph()'
sg2vgproto.o: In function `vg::Graph::operator=(vg::Graph const&)':
vg/include/vg.pb.h:95: undefined reference to `vg::Graph::CopyFrom(vg::Graph const&)'
sg2vgproto.o: In function `SG2VGProto::init(std::ostream*)':
hal2vg/sg2vgproto.cpp:29: undefined reference to `vg::Graph::~Graph()'
hal2vg/sg2vgproto.cpp:29: undefined reference to `vg::Graph::~Graph()'
hal2vg/sg2vgproto.cpp:29: undefined reference to `vg::Graph::Graph()'
sg2vgproto.o: In function `vg::Graph::operator=(vg::Graph const&)':
vg/include/vg.pb.h:95: undefined reference to `vg::Graph::CopyFrom(vg::Graph const&)'
sg2vgproto.o: In function `SG2VGProto::init(std::ostream*)':
hal2vg/sg2vgproto.cpp:29: undefined reference to `vg::Graph::~Graph()'
sg2vgproto.o: In function `operator()':
hal2vg/sg2vgproto.cpp:176: undefined reference to `vg::Graph::Graph(vg::Graph const&)'
sg2vgproto.o: In function `SG2VGProto::init(std::ostream*)':
hal2vg/sg2vgproto.cpp:29: undefined reference to `vg::Graph::~Graph()'
sg2vgproto.o: In function `bool stream::write<vg::Graph>(std::ostream&, unsigned long, std::function<vg::Graph (unsigned long)> const&)':
vg/include/stream.hpp:126: undefined reference to `vg::Graph::~Graph()'
vg/include/stream.hpp:126: undefined reference to `vg::Graph::~Graph()'
sg2vgproto.o: In function `SG2VGProto::~SG2VGProto()':
hal2vg/sg2vgproto.cpp:21: undefined reference to `vg::Graph::~Graph()'
sg2vgproto.o: In function `bool stream::write<vg::Graph>(std::ostream&, unsigned long, std::function<vg::Graph (unsigned long)> const&)':
vg/include/stream.hpp:126: undefined reference to `vg::Graph::~Graph()'
sg2vgproto.o:vg/include/stream.hpp:126: more undefined references to `vg::Graph::~Graph()' follow
collect2: error: ld returned 1 exit status
make: *** [hal2vg] Error 1

**Comment by glennhickey** [comment]
Should work now (via https://github.com/ComparativeGenomicsToolkit/hal2vg/commit/6b56b279d04e2601852fc791b27589758c3cde9a)
