### ISSUE TITLE
Compiling against recent versions of vg

### ISSUE THREAD

**Issue by alancleary** [ComparativeGenomicsToolkit/hal2vg#8]
Hi there. I haven't been able to build hal2vg against the current version of vg. Looking at the hal2vg commit logs and vg release dates, I was able to find a version of vg I could successfully build against - 1.6. The current release of vg is 1.9 and I'm concerned 2.0 might introduce breaking changes. So I'm curious, is there any plan to update hal2vg to compile against current versions of vg or, better yet, integrate the algorithm into vg's construct operator to add support for hal files?

**Comment by adamnovak** [comment]
I think @eldariont got building against current vg working in #9.

It would be nice to bring the whole project into the vg repo, or set up CI so we know when we need to update it to match the current vg. Or, better yet, use pkgconfig for linking and a fixed vg C++ API to build against.

**Comment by alancleary** [comment]
Thanks for the reply @adamnovak. Yes, linking against vg could certainly be better. Ideally you would just link libvg at compile time and call it good.

I made a Dockerfile for hal2vg that uses the vg Docker image as its base image so you don't necessarily have to build vg locally to get hal2vg up and running. Is this something you would want in the repo? I can make a pull request.

**Comment by adamnovak** [comment]
That would be nice to have; we could use it to add hal2vg to our
toil-vg pipelines.

**Comment by glennhickey** [comment]
hal2vg no longer builds against the vg project
